version: "3"
services:
  app:
    ports:
      - "8080:80"
    depends_on:
      - react-app
      - vue-app
      - angular-app
    build: .
  react-app:
    build:
      context: ./react-app
  vue-app:
    build:
      context: ./vue-app
  angular-app:
    build:
      context: ./angular-app
